### ISSUE TITLE
Response to reconciliation proposal?

### ISSUE THREAD

**Issue by runvnc** [joyent/nodejs-advisory-board#28]
Hi, whats the response to the reconciliation proposal?  Or, since it wasnt posted on this repo, does that mean it does not exist and doesnt need to be addressed directly?

**Comment by ben-page** [comment]
For reference: https://github.com/iojs/io.js/issues/978

**Comment by mikeal** [comment]
For reference, this was posted to `joyent/node` https://github.com/joyent/node/issues/9295 and was closed/locked as off-topic with a pointer to this repository for discussion. However, I would encourage people to comment *on the proposal itself* iojs/io.js#978 so that we can incorporate feedback in to the proposal. It is still a draft and should be a conversation not an ultimatum so I wouldn't want the JNAB to "respond" to it, I would prefer them to participate in the process of drafting it along with the rest of the community.

**Comment by isaacs** [comment]
Suggested questions to spur discussion, as I suggested (and got much head-nodding in response to) at the last JNAB meeting: https://groups.google.com/a/nodejs.org/d/msg/advisoryboard/1SgXQzyMTso/xhAf2klcELQJ

I would really like to see some collaboration from the Node.js team on this.  Specifically, @tjfontaine.

**Comment by fengmk2** [comment]
Ping JNAB members.

**Comment by piscisaureus** [comment]
See https://github.com/joyent/nodejs-advisory-board/pull/30.
